# Generated by Django 4.2.1 on 2023-05-16 15:40

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Roles',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('nom', models.CharField(max_length=30, verbose_name='Nom')),
                ('date_echeance', models.DateField(verbose_name="Date d'écheance")),
                ('type_document', models.CharField(blank=True, choices=[('projet_de_loi_ordinaire', 'PROJET DE LOI ORDINAIRE'), ('projet_de_loi_organique', 'PROJET DE LOI ORGANIQUE'), ('projet_ordonnance', "PROJET D'ORDONNANCE"), ('projet_decret', 'PROJET DE DECRET'), ('projet_communication', 'PROJET DE COMMUNICATION')], default='projet_de_loi_ordinaire', max_length=70, null=True, verbose_name='Type Document')),
                ('objet', models.CharField(max_length=500, null=True, verbose_name='Objet')),
                ('date_conseil', models.DateTimeField()),
                ('etats', models.CharField(choices=[('N/D', ' Nom demarrer'), ('ENCOURS', 'En cours'), ('TERMINER', 'Terminer'), ('ANNULER', 'Annuler')], default='N/D', max_length=20, null=True)),
                ('economie', models.TextField(max_length=2000, null=True, verbose_name='Economie')),
                ('observation_ct', models.TextField(max_length=2000, null=True, verbose_name='Observation')),
                ('recommandation', models.TextField(max_length=2000, null=True, verbose_name='Recommandation')),
                ('alert_impact', models.TextField(max_length=2000, null=True, verbose_name='Alert / Impact')),
                ('commentaire', models.TextField(max_length=2000, null=True, verbose_name='COmmentaire Du CT GOORE BI')),
                ('document', models.FileField(blank=True, null=True, upload_to='documents/', verbose_name='Document')),
            ],
            options={
                'verbose_name': 'Role',
                'verbose_name_plural': 'Roles',
            },
        ),
    ]
